### ISSUE TITLE
RPi Проблема с зависимостью конфига Swaylock

### ISSUE THREAD

**Issue by omletnet** [Ubuntu-Sway/Ubuntu-Sway-Remix#16]
При активации Swaylock экран становится белым а не размытым. Это из-за того, что ffmpeg, выполняющий это, не предустановлен.
~/.config/swaylock/lock.sh

**Comment by Sunderland93** [comment]
После установки ffmpeg проблема исчезает?

**Comment by omletnet** [comment]
Да

**Comment by omletnet** [comment]
> После установки ffmpeg проблема исчезает?

Да

**Comment by Sunderland93** [comment]
Я обновлю метапакет, включив туда ffmpeg. Спасибо за тестирование!

**Comment by omletnet** [comment]
> Я обновлю метапакет, включив туда ffmpeg. Спасибо за тестирование!

Вам спасибо
