### ISSUE TITLE
RPi Терминал Kitty не работает.

### ISSUE THREAD

**Issue by elmencho-bfg** [Ubuntu-Sway/Ubuntu-Sway-Remix#17]
Не может создать окно glfw.
Сам libglfw3-wayland (c/cpp) работает.

Думаю, что это проблема не системы или её сборки, а проблема самого терминала, т.к.  в Manjaro linux (для rpi)
терминалы с ускорением ГП тоже не работали (kitty, alacritty) из-за не подходящих OGL(ES).

Так что Kitty не надо добавлять в образ.

**Comment by Sunderland93** [comment]
Вы запускали на Raspberry Pi 3 или 4?

**Comment by omletnet** [comment]
> Вы запускали на Raspberry Pi 3 или 4?

4

**Comment by Sunderland93** [comment]
Kitty удален из базовой поставки начиная с USR 23.04
