### ISSUE TITLE
Прогноз погоды в SwayBar не отображается.

### ISSUE THREAD

**Issue by SpookerI** [Ubuntu-Sway/Ubuntu-Sway-Remix#20]
На стандартной конфигурации прогноз погоды, после запуска системы, не отображается. Необходимо перезагрузить конфигурцию, чтобы прогноз заработал.

**Comment by Sunderland93** [comment]
Приветствую. Модуль погоды отображается на панели только при наличии интернет соединения. Вероятно в вашем случае он загружается чуть раньше, чем появляется соединение. Я посмотрю чуть позже что можно изменить. Возможно стоит добавить небольшую задержку запуска модуля погоды.
