### ISSUE TITLE
apt update;apt upgrade returns with unresolvable error on linux kernel 5.15.0-47

### ISSUE THREAD

**Issue by davidthewatson** [Ubuntu-Sway/Ubuntu-Sway-Remix#21]
I downloaded and installed https://downloads.ubuntusway.com/latest/ubuntusway-22.04.1-desktop-amd64.iso

after rebooting, I ran:

    sudo apt update
    sudo apt upgrade

Everything completed successfully with one exception: the upgrade could not complete successfully because of an unresolved dependencies:

     linux-image-5.15.0-47-generic : Conflicts: linux-image-unsigned-5.15.0-47-generic but 5.15.0-47.51 is to be installed
     linux-image-unsigned-5.15.0-47-generic : Conflicts: linux-image-5.15.0-47-generic but 5.15.0-47.51 is to be installed

These unresolved dependencies did not show up in repeated apt update commands and were unresolved by issuing:

     sudo apt --fix-broken install

I'd like to contnue using the distro but this seems prohibitive with respect to package upgrades moving forward.

**Comment by davidthewatson** [comment]
Uploading output from update, upgrade, and fix-broken install. All run as root.

[update.txt](https://github.com/Ubuntu-Sway/Ubuntu-Sway-Remix/files/9486614/update.txt)
[upgrade.txt](https://github.com/Ubuntu-Sway/Ubuntu-Sway-Remix/files/9486615/upgrade.txt)
[install.txt](https://github.com/Ubuntu-Sway/Ubuntu-Sway-Remix/files/9486617/install.txt)

**Comment by davidthewatson** [comment]
I'm not sure how to fix the issue reported above, but the root cause appears to be:

    ~$ cat /etc/apt/sources.list.d/ubuntusway.list 
#deb https://ppa.launchpadcontent.net/ubuntusway-dev/stable/ubuntu jammy main
#deb-src https://ppa.launchpadcontent.net/ubuntusway-dev/stable/ubuntu jammy main

I reinstalled from the usb stick without error, then commented the ubuntusway ppa as above, then:

    sudo apt update
    sudo apt upgrade

which, of course, updated the kernel from the 46 to 47 minor release without issue.

I'm thinking there's something wrong with that package in the ubuntu sway ppa - probably the postinst.

**Comment by Sunderland93** [comment]
Hi. The Ubuntu Sway PPA does not contains any kind of packages that depends on linux kernel. In your upgrade.txt file I found that string:

`Failed to create symlink to vmlinuz-5.15.0-46-generic: Operation not permitted at /usr/bin/linux-update-symlinks line 64.`

which is why linux-image package stays unconfigured. I think this is an upstream issue whith packages being uploaded to the repo.

**Comment by davidthewatson** [comment]
> Hi. The Ubuntu Sway PPA does not contains any kind of packages that depends on linux kernel. In your upgrade.txt file I found that string:
> 
> 
> 
> `Failed to create symlink to vmlinuz-5.15.0-46-generic: Operation not permitted at /usr/bin/linux-update-symlinks line 64.`
> 
> 
> 
> which is why linux-image package stays unconfigured. I think this is an upstream issue whith packages being uploaded to the repo.

Hi. Thanks for your reply. 

Makes sense. I saw that too. The implication is that ubuntu upstream fixed the bug in the twelve hours since I posted this. The problem is that I found no combination of the usual fix-broken, dpkg -i, etc that fixed the state problem in apt once it occurred. 

I'll uncommonly the sway ppa today and hopefully apt doesn't melt. I must have just had bad luck with my installer timing yesterday. 

Thanks again for your help.

**Comment by davidthewatson** [comment]
Closing, problem resolved, assumed to be transient though I didn't track down the upstream corruption in the kernel packages postinst. Thanks!
