### ISSUE TITLE
apt quietly installs snapd - enhancement requested to prevent this

### ISSUE THREAD

**Issue by davidthewatson** [Ubuntu-Sway/Ubuntu-Sway-Remix#22]
I appreciate the design of ubuntu-sway that has taken steps to avoid snaps. 

However, I've quickly learned that the snap problem is more onerous than I realized because some popular packages such as chromium depend on snapd and so install it by default:

    $ sudo apt install chromium-browser
    Reading package lists... Done
    Building dependency tree... Done
    Reading state information... Done
    The following additional packages will be installed:
      *snapd* squashfs-tools
    The following NEW packages will be installed:
      chromium-browser snapd squashfs-tools
    0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
    Need to get 23.0 MB of archives.
    After this operation, 96.0 MB of additional disk space will be used.
    Do you want to continue? [Y/n] 

As a precaution, I think a reasonable improvement would be to have apt warn users when they are about to install and activate snapd without reading the fine print.

The solution is documented on askubuntu.com and I tested it here with my ubuntu-sway installation and it works as advertised.

The solution is simple:

    $ cat /etc/apt/preferences.d/nosnap.pref 
    # To prevent repository packages from triggering the installation of Snap,
    # this file forbids snapd from being installed by APT.
    # For more information: https://linuxmint-user-guide.readthedocs.io/en/latest/snap.html

    Package: snapd
    Pin: release a=*
    Pin-Priority: -10

and fully documented here:

https://askubuntu.com/a/1345401

Post installation of the nosnap.pref, you get:

    $ sudo apt install chromium-browser
    Reading package lists... Done
    Building dependency tree... Done
    Reading state information... Done
    Some packages could not be installed. This may mean that you have
    requested an impossible situation or if you are using the unstable
    distribution that some required packages have not yet been created
    or been moved out of Incoming.
    The following information may help to resolve the situation:
    
    The following packages have unmet dependencies:
     chromium-browser : PreDepends: snapd but it is not installable
    E: Unable to correct problems, you have held broken packages.

I'm happy to provide a PR if you kindly point me to the source code for ubuntu-sway. 

Thanks!

**Comment by Sunderland93** [comment]
Fixed in https://github.com/Ubuntu-Sway/iso-builder/commit/ca9cd8f18bbf6d13ce358572e8bb65bceb43266c
