### ISSUE TITLE
Add Flameshot to UbuntuSway

### ISSUE THREAD

**Issue by it-project-info** [Ubuntu-Sway/Ubuntu-Sway-Remix#24]
В последний раз, когда я пробовал sway (очень понравилось), камнем преткновения стала программа для скриншотов. Попробовал ставить Flameshot - не получилось настроить запуск по сочетанию клавиш, и на панели иконка не появлялась при старте. Из терминала Flameshot запускался

**Comment by amikha1lov** [comment]
Нужна именно программа с возможностью рисования и загрузки скриншота на сервер?

**Comment by Sunderland93** [comment]
Как насчет swappy? https://github.com/jtheoof/swappy

**Comment by it-project-info** [comment]
Это отличный вариант) Спасибо! 15.02.2023, 16:55, "Aleksey Samoilov" ***@***.***>: Как насчет swappy? https://github.com/jtheoof/swappy—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Sunderland93** [comment]
Хорошо. Будет добавлено в выпуск 23.04

**Comment by it-project-info** [comment]
У нас сменился домен, вместо it-project.info теперь 1kit.pro
 
Новые контакты:
Сайт: 1kit.pro
Эл. почта: ***@***.***
