### ISSUE TITLE
How to turn off the "help" window on startup?

### ISSUE THREAD

**Issue by ywpkwon** [Ubuntu-Sway/Ubuntu-Sway-Remix#27]
First of all, thanks for the great project! I really like it.

When logging in, there is always a `help` window (which shows sway shortcuts). I realized that it toggles with `mod + ?` key (which basically does `/usr/share/sway/scripts/help.sh --toggle`)

I want it to be hidden when start-up. 
So I added the line below to an user conf file `~/.config/sway/config.d/styling.conf`.
```
exec "/usr/share/sway/scripts/help.sh --toggle" 
```
My intention was, since the help window will be enabled by `/etc/sway/config.d/99-autostart-applications.conf`, and `~/.config/sway/config.d/*` is the last part of the whole configuration, I thought this part should turn the toggle down.

But the window is still shown when logging in. What is the proper way to hide it when logging in?
(Hopefully without touching the content in `/etc/sway/*`.)

**Comment by Sunderland93** [comment]
Comment line `[ -x "$(command -v nwg-wrapper)" ] && [ -f $HOME/.config/nwg-wrapper/help.sh ] && /usr/share/sway/scripts/help.sh` in `/etc/sway/config.d/99-autostart-applications.conf`

**Comment by ywpkwon** [comment]
Oh, I can definitely do that. But what if, for example, I don't have 'sudo' permission? Wouldn't it be better if there's a way to override it from the '.config/sway' side?

Or for example, when I might reinstall ubuntu-sway-remix later and deploy my dotfiles, I wish everything stays the same. But this solution will make me to touch a file inside '/etc'.

Of course I can make a script to search and comment out the particular line, but I was wondering if there's a better way. Thanks for your answer though!

**Comment by Sunderland93** [comment]
On-demand "help" overlay introduced in https://github.com/Ubuntu-Sway/ubuntu-sway-default-settings/commit/ca59f8f80de765c1ccf1c05ab8a1b55d54097069 and will be added in Ubuntu Sway Remix 24.04
