### ISSUE TITLE
Authenticate user...

### ISSUE THREAD

**Issue by bluesfreak72** [Ubuntu-Sway/Ubuntu-Sway-Remix#42]
I'm booting it up on Gentoo as the host machine and Qemu/KVM/Libvirt.  I get a login screen right before the window manager should come up.  I've tried everything I can think of.  I've set the video driver to VirtIO.  What's the default username / password combo???

**Comment by Sunderland93** [comment]
Default user/password is "ubuntu"/no password, but the password prompt should not appear. Most likely, hardware graphics acceleration is not working for you, which is why Sway does not start. Please see https://github.com/Ubuntu-Sway/Ubuntu-Sway-Remix/wiki/Virtualization
