### ISSUE TITLE
Not seeing pair request confirmation when pairing a bluetooth device

### ISSUE THREAD

**Issue by glenneth1** [Ubuntu-Sway/Ubuntu-Sway-Remix#44]
I am using the Ubuntu sway remix on a HP laptop.  When trying to pair a Bluetooth mouse the pairing request fails and I am not seeing a confirmation window to accept the pairing request.  This is when using the Bluetooth module on waybar and Bluetooth manager added afterwards.

**Comment by brianpooe** [comment]
I am facing the same thing on my ausus desktop

**Comment by bebekSambal** [comment]
dont try to install blueman ?

**Comment by Sunderland93** [comment]
Ubuntu Sway Remix now uses [Bluetuith](https://github.com/darkhz/bluetuith). If issue is still relevant - feel free to reopen it
