### ISSUE TITLE
Просьба реализовать разные сборки Ubuntu-Sway-Remix

### ISSUE THREAD

**Issue by devakant** [Ubuntu-Sway/Ubuntu-Sway-Remix#5]
Реализовать сборки по наличию программ.

Минимальную, в которую будет входить к примеру: 
DE, Браузер, программа для просмотра фотографий, скриншотер, плеер. (возможно ещё что-то, нужно обсуждать).

Расширенную.
Кроме выше перечисленного: 
Офисные программы. GIMP, telegram, thunderbird и другие (возможно ещё что-то, нужно обсуждать).

Это нужно для того, чтобы те кто любит минимальные сборки без лишнего мусора, потом не тратили время на удаление лишнего.
А тем кому всё равно могли поставить расширенную и не парится.

**Comment by BlitDev** [comment]
Неплохая идея, поддерживаю

**Comment by Sunderland93** [comment]
Начальная поддержка минимальной установки https://github.com/Ubuntu-Sway/calamares-settings-ubuntu-sway/commit/d4d9217d7ab9e5f3076f5879d6348ce617c90d2f

**Comment by Sunderland93** [comment]
Делать отдельные версии с бОльшим набором софта не планируется.
