### ISSUE TITLE
/etc/profile.d/sway.sh is missing

### ISSUE THREAD

**Issue by JohannesPertl** [Ubuntu-Sway/Ubuntu-Sway-Remix#51]
In the wiki it is mentioned to edit `/etc/profile.d/sway.sh`: https://github.com/Ubuntu-Sway/Ubuntu-Sway-Remix/wiki/Nvidia-cards

However, this file does not exist

**Comment by Sunderland93** [comment]
Please read carefully:

`Note: Starting with Ubuntu Sway Remix 23.04, the Nvidia driver configuration is automatically detected. All you have to do is install Nvidia driver itself and enable Nvidia DRM Modesetting as mentioned below.`

in the Wiki
