### ISSUE TITLE
blank screen after booting from ISO on real hardare

### ISSUE THREAD

**Issue by iharh** [Ubuntu-Sway/Ubuntu-Sway-Remix#53]
I tried installing ubuntusway-23.10-desktop-amd64.iso in kvm/qemu virtual machine - everything was fine
Then - created a boot USB, booted from it (with nomodeset, which is required in my case for all linux distros).
Then - got the tuigreet window
Then - entered an "ubuntu" username and empty pwd
Then - the screen became blank (it quickly blinks once in 15-20 seconds with some tuigreet artifacts and quickly goes black again).

Note: I'm using embedded graphics card and AMD Ryzen 7:
```
CPU: 8-core AMD Ryzen 7 5700G with Radeon Graphics (-MT MCP-)
```

**Comment by Sunderland93** [comment]
> with nomodeset, which is required in my case for all linux distros

The reason is this. Sway doesn't support UMS, only KMS.

**Comment by iharh** [comment]
> > with nomodeset, which is required in my case for all linux distros
> 
> The reason is this. Sway doesn't support UMS, only KMS.

Thank you very much, @Sunderland93 . But what do I need to do? Can I do something in order to collect logs/systemd-journal in some way?
Are there any other way to install ubuntu-sway-remix (probably with cmd-line only) ???

**Comment by iharh** [comment]
@Sunderland93 : BTW, it is not an issue in case if I boot at the machine with intel CPU and embedded video.

**Comment by iharh** [comment]
The root cause is my kvm-switch hardware. Without it everything is fine.
