### ISSUE TITLE
lock in nwg-bar does not lock the screen

### ISSUE THREAD

**Issue by Fuseteam** [Ubuntu-Sway/Ubuntu-Sway-Remix#59]
it appears that `lock.sh` is missing in `~/.config/swaylock/` on a fresh install

**Comment by pcaton-stack** [comment]
Any idea how to fix it?

**Comment by Fuseteam** [comment]
an quick fix is to edit `~/.config/nwg-bar/bar.json` to use swaylock directly like this
```
{
   "label": "Lock",
   "exec": "swaymsg exec /usr/share/sway/scripts/swaylock.sh",
   "icon": "system-lock-screen"
 },
```

**Comment by pcaton-stack** [comment]
Hello Rahammetoela,

Thank you so much for your quick response. I just edited that file and it works perfectly!

Thank you so much,

Peter

**Comment by Sunderland93** [comment]
Fixed in 24.04.1

**Comment by NoelleTGS** [comment]
I'm on 24.04.1 and `lock.sh` is still missing for me, the only contents of `~/.config/swaylock` is a file named `config`. 
Closing the laptop lid does not lock the screen either as it did on my old installation, though I do not know whether that is the same issue.

**Comment by Fuseteam** [comment]
i suspect that it may be missing if you upgraded to 24.04.1 because the folder already exists

**Comment by Fuseteam** [comment]
for customization a solution might be to just copy `/usr/share/sway/scripts/swaylock.sh` to `~/.config/swaylock` like so
```
cp /usr/share/sway/scripts/swaylock.sh ~/.config/swaylock/lock.sh
```

**Comment by Sunderland93** [comment]
> i suspect that it may be missing if you upgraded to 24.04.1 because the folder already exists

Configs, that located in /home, are note upgraded on system update. You need to copy it manually from /etc/skel/

**Comment by Fuseteam** [comment]
> > i suspect that it may be missing if you upgraded to 24.04.1 because the folder already exists
> 
> Configs, that located in /home, are note upgraded on system update. You need to copy it manually from /etc/skel/

only `config` there aswell

**Comment by NoelleTGS** [comment]
I don't have any files at all in `/etc/skel/`.

**Comment by Fuseteam** [comment]
> I don't have any files at all in `/etc/skel/`.

`ls -a`?

**Comment by NoelleTGS** [comment]
Sorry I actually reinstalled with the 24.04.1 iso, though the problem still doesn't seem to be fixed. `~/.config/swaylock` still only has the `config` file, and while the skel directory has files in it now, `/etc/skel/.config/swaylock/` still only has that same `config` file.

**Comment by Sunderland93** [comment]
`nwg-bar` now points to `/usr/share/sway/scripts/lock.sh`
