### ISSUE TITLE
Raspberry Pi build

### ISSUE THREAD

**Issue by Sunderland93** [Ubuntu-Sway/Ubuntu-Sway-Remix#6]

**Comment by syorito-hatsuki** [comment]
Ожидаю

**Comment by Sunderland93** [comment]
Beta image of Ubuntu Sway Remix for RPi is released. You can download it here: https://downloads.ubuntusway.com/raspberrypi/20220730/

Works only on Raspberry Pi 3b, 3b+, 4 and 400
